services:
  symptochron-app:
    image: node:22-alpine
    working_dir: /app
    env_file: .env # <-- HIERMIT LIEST DOCKER DIE REPARIERTE .ENV-DATEI EIN!
    volumes:
      - .:/app
      - symptochron-data:/app/server/data
      - /app/node_modules
    ports:
      - "3050:3000"
    command: sh -c "npm install && npm run build && node dist/server.cjs"
    restart: always

volumes:
  symptochron-data:
